### ISSUE TITLE
Baskets causing the game to crash

### ISSUE THREAD

**Issue by Kuverr** [DragonsPlusMinecraft/CreateCentralKitchen#74] opened 2024-01-22 11:24 UTC
### Minecraft Version

1.20.1

### Describe the Bug

Baskets causing the game to crash

### Reproduction Steps

1. Place a basket
2. Game crashes
or
1. Place a basket without central kitchen installed
2. Leave the game
3. Install cck
4. Enter the world
5. Game crashes

### Expected Result

The game doesn't crash

### Crash Report or Log

https://pastebin.com/QfcuSJbn

### Other Mods

Rechiseled: Create
Highlight
Create Utilities
YUNG's Menu Tweaks
Lan Server Properties
3d-Skin-Layers
Rechiseled
More Red
YUNG's Extras
Jade
Thermal Innovation
Create Crafts & Additions
ModernFix
AmbientSounds
Model Gap Fix
Tectonic
Fluidlogged
Iron Chests
Bountiful
Mekanism: Additions
TexTrue's Embeddium Options
mutil
CreativeCore
Simple Inventory Sorter
MrCrayfish's Furniture Mod
FramedBlocks
Iron Furnaces
SuperMartijn642's Config Library
Polymorph
Create: Connected
Connected Glass
Jade Addons
AppleSkin
Mekanism: Tools
Antique Atlas
Furnish
Mekanism
EntityCulling
AE2WTLib
YUNG's Better Jungle Temples
Create: Design n' Decor
Chunk Loaders
CoFH Core
Nature's Compass
Titanium
Create Enchantment Industry
Create: Interiors
Create Track Map
CC:C Bridge
YUNG's Better Witch Huts
Just Enough Items
Puzzles Lib
Corpse
Create Slice & Dice
Advanced Peripherals
Mekanism: Generators
Construction Wand
Collective
EMI
Chalk
Entity Model Features
Fusion
YUNG's Better Desert Temples
YUNG's Better Strongholds
Macaw's Trapdoors
YetAnotherConfigLib
Thermal Integration
Monobank
Memory Leak Fix
Kotlin for Forge
Capable Composters
GoProne
Architectury
EMI Trades
Spyglass Improvements
Entity Texture Features
Radium
Observable
Exposure
Create
YUNG's Better Dungeons
SuperMartijn642's Core Lib
Thermal Expansion
YUNG's API
tetra
Ferrite Core
YUNG's Bridges
ItemLocks
Mighty Mail
Oculus
Searchables
Framework
Create: Oxidized
Curios API
Cloth Config v10 API
Chefs Delight
tetracelium
Functional Storage
Capable Cauldrons
AEInfinityBooster
Controlling
YUNG's Better Mineshafts
Applied Mekanistics
Tree Harvester
Seamless
Explorify
CC: Tweaked
Magnum Torch
YUNG's Better End Island
Saturn
KleeSlabs
CosmeticArmorReworked
Embeddium
EMIffect
Create: The Factory Must Grow
Create: Bells & Whistles
Mouse Tweaks
Sound Physics Remastered
Right Click Harvest
More Red x CC:Tweaked Compat
Comforts
Balm
Macaw's Doors
Applied Energistics 2
Smooth Boot (Reloaded)
ImmediatelyFast
Infinity Buttons
Useful Spyglass
YUNG's Better Ocean Monuments
Traveler's Backpack
Create: Steam 'n' Rails
Create Sifter
AE2 Things
YUNG's Better Nether Fortresses
Supplementaries Squared
Thermal Foundation
Kambrik
Create Deco
Supplementaries
Farmer's Delight
Moonlight Library
Embeddium++
Extra Compat
Tom's Peripherals
Create Central Kitchen 

### Mod Version

1.3.9.d

### Forge Version

47.2.0

**Comment by MarbleGateKeeper** [comment] 2024-02-05 05:00
Imcompatible with Computer Craft. I'll figure out a fix. Duplicate of #69

**Closed as completed** 2024-02-05 05:26 UTC
Labels: bug, duplicate, crash, mod interaction
