### ISSUE TITLE
Game fails to load if Useful Spyglass is installed

### ISSUE THREAD

**Issue by ElRichiRicon** [DragonsPlusMinecraft/CreateCentralKitchen#88] opened 2024-04-08 04:42 UTC
### Minecraft Version

1.20.1

### Describe the Bug

The game stops loading and closes during the mod scanning phase if both CCK and Useful Spyglass are installed.

NeoForge 47.1.104
Create 0.5.1f
CCK 1.13.2
Useful Spyglass 0.6.0

[prism log](https://pastebin.com/mrew6vJu)

BrokenK3yboard/UsefulSpyglass#9

**Comment by RaymondBlaze** [comment] 2024-04-08 07:00
Useful Spyglass is responsible for the crash as it bundles the NeoForge specific MixinExtras artifact instead of the Forge one, which is not suitable for mods under NeoForge 20.2.84.

I'm closing this since the developer of Useful Spyglass has confirmed the exact issue and will be patching it in next release.

**Closed as completed by RaymondBlaze** 2024-04-08 07:00 UTC
Labels: bug, not on my end
