### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Pancaros57** [DragonsPlusMinecraft/CreateCentralKitchen#56] opened 2023-06-29 14:43 UTC
### Minecraft Version

1.19.2

### Describe the Bug

I have a server setup in Oracle Cloud Hosting
and when I try to start up the server with my modpack it doesn not start up and shows Create Central Kitchen as the cause
[crash.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11906899/crash.txt)

### Reproduction Steps

1.install the mod with Forge 43.2.14
2.Startup the server
3.See the crash
...

### Expected Result

for it to crash and give me an issue about "Create Central Kitchen"

### Mod Version

1.3.7.d

### Forge Version

43.2.14

**Comment by MarbleGateKeeper** [comment] 2023-06-29 14:46
Duplicate of #44.
Please delete config of CCK completely.

**Closed as completed** 2023-06-29 14:47 UTC
Labels: bug
